
lgb_params:
  'objective': 'binary'
  'metric': 'auc'
  'boosting_type' : 'gbdt'
  'learning_rate': 0.05
  'bagging_freq': 1
  'bagging_fraction': 0.9
  'num_leaves': 8
  'force_col_wise': True
  'feature_fraction': 0.9




